FROM node:21.6.2-slim
WORKDIR /backend

COPY ./package.json .
COPY ./pnpm-lock.yaml .

RUN corepack enable
RUN corepack prepare pnpm@8.6.12 --activate

RUN pnpm install

COPY ./ ./

RUN pnpm exec playwright install --with-deps

RUN pnpm run build

CMD [ "pnpm", "run", "test:e2e" ]
