include /etc/nginx/mime.types;

server {
    listen 80;
    server_name affichage.online;
    charset utf-8;

    keepalive_timeout 5;

    location / {
        autoindex on;
        root /data/www/;
        add_header Access-Control-Allow-Origin *;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}