services:
  # -----------------------------------------------
  # ------------------- BACKEND -------------------
  # -----------------------------------------------
  backend:
    container_name: bulhma-backend-perf
    build:
      context: ./backend
    env_file:
      - ./env.perf
    depends_on:
      - db-tests
    networks:
      - backnet-perf-tests

  # -----------------------------------------------
  # ------------------- NGINX ---------------------
  # -----------------------------------------------
  nginx:
    container_name: bulhma-nginx-perf-tests
    image: nginx:1.25.1-alpine
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-perf.conf:/etc/nginx/nginx.conf
    networks:
      - backnet-perf-tests
    restart: always

  # -----------------------------------------------
  # ------------------- BACKEND -------------------
  # -----------------------------------------------
  backend-perf-tests:
    container_name: bulhma-backend-perf-tests
    build:
      dockerfile: Dockerfile.perf
      context: ./backend
    command: pnpm run test:perf
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    env_file:
      - ./env.test
    depends_on:
      - backend
    networks:
      - backnet-perf-tests

  # -----------------------------------------------
  # --------------------- DB ----------------------
  # -----------------------------------------------
  db-tests:
    container_name: bulhma-db-perf-tests
    image: postgres:15.3-alpine
    env_file:
      - ./env.test
    networks:
      - backnet-perf-tests

networks:
  backnet-perf-tests:
