name: Nightly e2e
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  e2e:
    if: github.ref == 'refs/heads/develop'
    name: E2E tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build e2e docker-compose
        run: ./build_e2e_test.sh
      - name: Launch e2e tests
        run: ./start_e2e_test.sh
  performance:
    if: github.ref == 'refs/heads/develop'
    name: Perf tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build perf docker-compose
        run: ./build_perf_test.sh
      - name: Launch perf tests
        run: ./start_perf_test.sh
